### ISSUE TITLE
Chat option to connect riders and drivers

### ISSUE THREAD

**Issue by sarahbrace** [SnowpoolApp/icare#11]
Riders and drivers need to be able to communicate once they have connected on a ride. A chat box becomes an option to refine plans, etc.

**Comment by Asimov4** [comment]
I thought this was already supported in icare. What kinds of improvements do you expect?

**Comment by sarahbrace** [comment]
I’m not sure I understand what care is — I included it as a ticket to make sure we can include this feature in the app.

**Comment by Asimov4** [comment]
Makes sense! I was referring to this feature:
![image](https://user-images.githubusercontent.com/897911/92542109-c22cf400-f1fc-11ea-99c9-ad7f03c7c3c3.png)
https://snowpool-app.herokuapp.com/conversations/1

I'll update the issue decription to clarify that this ticket is about porting the chat feature over to the mobile application.

**Comment by Asimov4** [comment]
I was referring to this feature: https://snowpool-app.herokuapp.com/conversations/1
![image](https://user-images.githubusercontent.com/897911/92542109-c22cf400-f1fc-11ea-99c9-ad7f03c7c3c3.png)

**Comment by sarahbrace** [comment]
Ah, got it! Sorry, I didn’t see this last time I went through the app so missed it. Thanks!

**Comment by Asimov4** [comment]
Closing the ticket because the feature is already implemented.
