### ISSUE TITLE
Indicate how many seats are available in car (driver)

### ISSUE THREAD

**Issue by sarahbrace** [SnowpoolApp/icare#7]
As a driver, it would be helpful to indicate how many seats are available in the car for the ride I am offering.
For a given trip and date, Is it possible to:

1.  add a menu/option (or other too)l to indicate how many riders I can take? 

2. Once a seat is taken,  update the # of seats that remain?

**Comment by Asimov4** [comment]
I cut this as a feature request for the main open source project: https://github.com/diowa/icare/issues/549

**Comment by Asimov4** [comment]
This was implemented by https://github.com/SnowpoolApp/icare/pull/15 during the hackathon!
Closing.
