### ISSUE TITLE
Driver indicates available space for snowboards and skis 

### ISSUE THREAD

**Issue by sarahbrace** [SnowpoolApp/icare#8]
Drivers should be able to share the space they have for additional skis and snowboards. 

1. When setting up the Driver's Ride page -- on a given date -- allow for a blank space or drop-down option to indicate how many boards or skis they can take (in addition to passengers). 

2. When ride is confirmed by passenger, drop # of ski/snowboard spaces accordingly?

**Comment by Asimov4** [comment]
This was implemented by https://github.com/SnowpoolApp/icare/pull/15
Closing.
